PYTHON = python3 #archive
SCRIPT = main.py

# Regla por defecto
all: execute

# Regla para ejecutar el script
execute:
	$(PYTHON) $(SCRIPT)

# Regla para limpiar (si fuera necesario)
clean:
	# No es necesario en este caso, pero se podría agregar para otros archivos
	rm -f *.pyc